# Generated by Django 4.2.4 on 2023-08-26 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro'),
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
