# Generated by Django 4.2.4 on 2023-08-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autores', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13)),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('editorial', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
